// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.TestCardGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("brand")]
        public string Brand { get; set; }

        [JsonProperty("count")]
        public long? Count { get; set; }

        [JsonProperty("cards")]
        public Card[] Cards { get; set; }

        [JsonProperty("owner")]
        public Owner Owner { get; set; }
    }

    public partial class Card
    {
        [JsonProperty("cvv")]
        public long? Cvv { get; set; }

        [JsonProperty("issuer")]
        public string Issuer { get; set; }

        [JsonProperty("id")]
        public Guid? Id { get; set; }

        [JsonProperty("number")]
        public string Number { get; set; }

        [JsonProperty("expiration")]
        public string Expiration { get; set; }

        [JsonProperty("brand")]
        public string Brand { get; set; }

        [JsonProperty("number_alt")]
        public NumberAlt NumberAlt { get; set; }
    }

    public partial class NumberAlt
    {
        [JsonProperty("masked")]
        public string Masked { get; set; }

        [JsonProperty("unmasked")]
        public string Unmasked { get; set; }

        [JsonProperty("last4")]
        public long? Last4 { get; set; }
    }

    public partial class Owner
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("address")]
        public Address Address { get; set; }

        [JsonProperty("avatar")]
        public Uri Avatar { get; set; }
    }

    public partial class Address
    {
        [JsonProperty("street")]
        public string Street { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("zipCode")]
        public string ZipCode { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
